### ISSUE TITLE
problem: Logging with systemd doesn't enable users to split out logs to /var/log

### ISSUE THREAD

**Issue by tk-hendrik** [csirtgadgets/bearded-avenger#169]
Hi Wes,

as mentionend in our last flights regarding ubuntu 16 integration and systemd - I'm still missing local logfiles. Of course they are accessible with journalctl but only there.

As soon as I run the cif-*|csirtg-smrt services behind of supervisord I'll get my local logs as expected.

Question to ask: "What's your preffered way?" 
1) Running your daemons from supervisord getting the logs via config directive or
2) get rid of supervisord and use the (confusing) power of systemd but adapt logging routines to log to a filehandle?

-Hendrik

**Comment by wesyoung** [comment]
in centos we just got rid of supervisord and went all systemd since that's probably what most admins will want to leverage anyway (imo supervisord was just a less hacky way to control things when systemd env stuff did not exist).

imo: almost always try to go with the default on the platform... it might be more confusing in the short term as the platform transitions, but there are probably work-arounds to make logging more accessible(?)

**Comment by tk-hendrik** [comment]
OK - no more invest in supervisord.
What do you think about a PR bringing a new cli parameter like "logdir" adding an additional logger file handle?

**Comment by wesyoung** [comment]
if it solves a discrete problem for you, we rarely turn away PRs :)

**Comment by wesyoung** [comment]
also.. it's probably a good idea, esp if you match it up with an os.getenv('CIF_LOGGING_PATH'), so by default it works as-is, but with the correct env var / flag set.. it spins up an extra handler.

**Comment by tk-hendrik** [comment]
> if it solves a discrete problem for you, we rarely turn away PRs :)

even if I wish - I'm not the central of the universe :)
Yes, it would solve my problem but of course it would be nice if more than just me would profit from this feature.

Background:
If one is forwarding all system logs to a central system also the cif logs would be forwarded if it's logging through systemd/journalctl. If one then is playing with cif and DEBUG messages those poor forwarding system will get to much useless log messages.

**Comment by wesyoung** [comment]
ah. makes sense. the way i look at the world. if you're having this issue, a thousand other people probably are or will.. which is kinda why we follow the zmq C4 process when it comes to this stuff:

https://rfc.zeromq.org/spec:42/C4

if it's a good feature, everyone will benefit. if it's a useless feature, eventually it'll get papered over. if it's a great feature but poorly implemented, it will get fixed by future PRs. with things like this, it's probably good to think through it a little... since we're in an alpha state still, i'm more concerned about testing things out and figuring out what works.. if we were closer to RC's, i'd probably scrutinize a little... but also point at the new alpha's for the next version and suggest we idea bash over there...

so as long as it's not a PR that tries to solve more than one problem and re-writes entire swaths of code at once... if it helps you, it probably helps us [we might just not know it yet .. or have had the cycles to think through it]. least that's how i think about these kinda things... 

your thought process makes nothing but sense to me, esp given the background.
