### ISSUE TITLE
problem: missing Cisco Umbrella 1 Million (whitelist)

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/bearded-avenger#184]
Consider adding or switching to this top 1 million feed. 

https://blog.opendns.com/2016/12/14/cisco-umbrella-1-million/

**Comment by JustinAzoff** [comment]
A 1-million entry whitelist would complicate things.  Doable, but backend would probably need to cache it persistently instead of doing the tags=whitelist search at feed generation time.

**Comment by wesyoung** [comment]
right now that's how we use the alexa list, but what we do is modify the confidence stuff inbound too... so top10 is 90% confidence, etc... ex:

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/src/rules/default/alexa.yml
https://github.com/csirtgadgets/csirtg-smrt-py/tree/master/test/alexa

i like where you're headed with the caching idea, esp since now the db is so small...

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/bearded-avenger/pull/232
