### ISSUE TITLE
problem: elasticsearch missing v5 compatibility

### ISSUE THREAD

**Issue by invisiblebits** [csirtgadgets/bearded-avenger#236]
Hello,

Elasticsarch 5.x does not support _timestamp and _ttl mappings, and CIF v3 pushing method uses _timestamp.

In order to integrate CIF v3 with Elasticsearch, you have to use Elasticsearch v2.4.x. Elasticsarech v5.x is not compatible.

My two cents!

**Comment by wesyoung** [comment]
do you have a work-around? something that could be conjured up as a PR? i'm guessing its something we'd also need to fix upstream with elasticsearch-dsl too since we're using that to touch the metafield:

https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/store/zelasticsearch/indicator.py#L65

**Comment by Lefnui** [comment]
Do you plan to support both v2.4 and v5 at the same time? Or just move to v5?
I need to have support for v5, so I'll look into this issue

**Comment by wesyoung** [comment]
i would like to support both because not everyone wants to use v5 yet (i wouldn't use it in prod, i've been burned too many times before for stuff like this.. but i understand why others might and we should build towards that so you guys can test it for people like me :)).

based on my cursory glance, the only real diff that stands out is how to handle a few of the meta fields. i had initially looked at what the elasticsearch-py bindings supported and i think something was off, but it's been a while. so i was giving it a few months to see if those issues shook out (i can't remember what they were).

but yes. for all our sanity, the way the plugin was written it should just be a few simple re-maps to make it work with both and should be done. does that make sense?

**Comment by patche81** [comment]
Any update/progress on this ?

**Comment by wesyoung** [comment]
not unless someone has a PR to submit(?) :)

**Comment by wesyoung** [comment]
if anyone's watching, i think i have this fixed for v5.4, but with the changes it'll break backwards compatibility with 2.x (which i think is OK given how easy it is these days to dockerize es).  PR en-route today or tomorrow...
