### ISSUE TITLE
CIF Client and Export for 3rd Party Integration

### ISSUE THREAD

**Issue by schizophrenchen** [csirtgadgets/bearded-avenger#271]
Hi Wes,
me again :) I am preparing to integrate v2 and v3 into SIEM. To do that, i generate a CSV export of indicators to be consumed by a data collector which sends it to SIEM.

With v2, there was the option to not just export to CSV, you could even chose which fields should go into the export. This option is gone in CIF client v3. Is there a reason? Does it come back?
Unfortunately i need to first go the v3 path, as the SIEM data collector is not supported to run on Ubuntu.

Also the data schema for indicators changed dramatically. Is that by design or is there any parsing issue i might face which looks like fewer columns in the unfiltered export of v3 indicators?

I am aware, i can use AWK and friends to get rid of unwanted fields, but existing integration with SIEM needs to be patched and SIEM content needs to be adjusted because the data schema has changed. Therefor i wanted to re-insure before i go down that path.

Thanks,
Markus

**Comment by wesyoung** [comment]
hiya,

1. https://github.com/csirtgadgets/bearded-avenger-sdk-py/issues/48 (client is def missing the --fields flag, happy to accept a PR if you get to it before i do)

1. we haven't really gone through "what's presented by default" with any amount of scrutiny just yet. in this release we are def aiming for "simpler is better", but that also requires a working --fields flag :) (there are lots more fields behind the scenes)

1. nope you're not missing anything, we're just still in the "get it working, somewhat error free" right now. but we're getting much closer (esp because of feedback like this) at taking a first round stab at the doc as well as, well.. what fields get presented by default.. (as we work through the doc examples).

does that make sense?
