### ISSUE TITLE
CIFv3 Questions

### ISSUE THREAD

**Issue by Nibor62** [csirtgadgets/bearded-avenger#282]
Hi,

Sorry by advance for the imprecise title.
I have some questions about this new version of CIF :
* It seem that you have really poor documentation on this version, so if I want to help, is there somewhere I can go to find some global architecture presentation to grasp more easily the global scheme ?
* Wouldn't python3 be helpful for code simplicity and maintenance for incoming years ?

**Comment by wesyoung** [comment]
* because we haven't quite hit the beta stages, we haven't put a lot of effort into the doc, always happy to accept edits and PRs
* checkout https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki -- which is where most of the higher level doc is going (i haven't linked them yet, it's not ready)
* the core is developed on py3 and then we test deploy on ubuntu14|16 and CentOS7 which uses py2 by default. all the components are tested using travis and py2|py3 to ensure they're cross compatible. 

the reality is; very few OS's ship py3 as the default interpreter, and while we develop in py3, py2 is going to be the default for a very long time .. until you see distro's like RedHat ship it as *the* default (meaning /usr/bin/python is version 3).

make sense?

**Comment by wesyoung** [comment]
also; a lot of our older higher level stuff can be found here:

http://csirtgadgets.org/
https://github.com/csirtgadgets/massive-octo-spice/wiki/The-CIF-Book

we don't spend a ton of effort on more than that (although others have) because we're just busy writing code (really hard to do both). great opportunity for others to jump in and make pretty pictures, etc... always happy to link to others work (or barrow from, etc).

**Comment by Nibor62** [comment]
On most Linux distribution Python2 is still the default interpretor indeed, but what is keeping you from installing Python3 and using it for CIF ? Both version can coexist quite happily nowdays !

**Comment by wesyoung** [comment]
the example deployment kits are examples for an "out of the box" deployment. it assumes you're going to customize it for an environment that you're comfortable with. if [in production] you're comfortable with py3, you should def adapt your deployment strategy for it.

from experience, the majority of the world, is not quite there yet (which is why py3 isn't the default). additionally, while *most* of the underlying libs are py3 supported, pyt3 is a different enough of a language in and of itself not not all underlying libs have been battle tested enough for most production env's to be comfortable with. esp those that leverage various style C backends.

so while simpler python scripts can co-exists fairly well, things with more complex dependencies have a tougher time in production running, let alone co-existing. BUT- that's also why we try to give set of example playbooks, develop as much as we can in py3 and give users the ability to run faster in the environment that fits their requirements, but default to the hooks that *most* production environments would use so that it's a stable experience.

**Comment by Nibor62** [comment]
That's make sense;

Another one : same question as for cifv2, is there any way to disable ASN requests (and any other requests that may be done to gather intelligence at insert) ?

**Comment by wesyoung** [comment]
there will be in the next release. moving to something more local by default and turning off hunters by default..

**Comment by Nibor62** [comment]
Thank for your answers, can't wait to test it !

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/bearded-avenger/releases/tag/3.0.0a18
